# this build is designed to replicate the Travis CI workflow
name: Build with Maven

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        java-version: [ 8 ]
        maven: [ '3.6.3']

    runs-on: ${{ matrix.platform }}
    env:
      PLATFORM: ${{ matrix.platform }}
      JAVA_VERSION: ${{ matrix.java-version }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: adopt
          cache: maven
      
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.5.1
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven }}

      # Enable caching dependencies to speed up the build
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2

      - name: Check out kenya core repository
        uses: actions/checkout@v3
        with:
          repository: palladiumkenya/openmrs-module-kenyacore
          ref: openmrs-2.4.x-upgrade

      - name: Compile and build kenya core repository
        run: mvn clean install -DskipTests

      - name: Check out kenya UI repository
        uses: actions/checkout@v3
        with:
          repository: palladiumkenya/openmrs-module-kenyaui
          ref: master

      - name: Compile and build kenya UI repository
        run: mvn clean install -DskipTests


      - name: Check out kenyaemrorderentry
        uses: actions/checkout@v3
        with:
          repository: palladiumkenya/openmrs-module-kenyaemrorderentry
          ref: master

      - name: compile and build kenyaemrorderentry
        run: mvn clean install -DskipTests

      - name: Check out facilityreporting
        uses: actions/checkout@v3
        with:
          repository: palladiumkenya/openmrs-module-facilityreporting
          ref: 037bb36d

      - name: compile and build facilityreporting
        run: mvn clean install -DskipTests

      - name: Check out kenyaemrdq
        uses: actions/checkout@v3
        with:
          repository: palladiumkenya/openmrs-module-kenyadq
          ref: 1.2

      - name: compile and build kenyaemrdq
        run: mvn clean install -DskipTests


      - name: Check out kenyaemr repository
        uses: actions/checkout@v3
        with:
          repository: savannahghi/openmrs-module-kenyaemr
          ref: v17.0.3

      - name: Compile and build kenyaemr repository
        run: mvn clean install -DskipTests

      - name: Check out hospital core repository
        uses: actions/checkout@v3
        with:
         repository: savannahghi/openmrs-module-hospitalcore
         ref: develop

      - name: Compile and build hospital core repository
        run: mvn clean install -DskipTests

      - name: Check out inventory core repository
        uses: actions/checkout@v3
        with:
          repository: savannahghi/openmrs-module-inventory
          ref: main

      - name: Compile and build inventory core repository
        run: mvn clean install -DskipTests

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version --file pom.xml
      - name: Build with Maven
        run: mvn test --batch-mode --file pom.xml
